### ISSUE TITLE
Contributions of projects 

### ISSUE THREAD

**Issue by bartboogmans** [ros-maritime/awesome-maritime-robotics#1]
I don't know if we want to sort projects/modules component wise or project wise. I think having available modules in a list rather than complete projects would be more valuable, so people using the overview can mix and match to their needs. 

To get the ball rolling I'm proposing to add the project from University of Rhode Island from [this post](https://discourse.ros.org/t/release-of-ros-mvp/29367) to the list. 

Control effort generation - Control effort allocation:
- [MVP-Control](https://github.com/uri-ocean-robotics/mvp_control): A generic vehicle low-level vehicle controller (implements a control allocation algorithm with quadratic programming).

Planning/Guidance mission-planning:
- [MVP-Mission](https://github.com/uri-ocean-robotics/mvp_mission): A generic behavior-based state-oriented mission planner. It contains common behaviors for marine guidance.

Simulation:
- [Stonefish](https://stonefish.readthedocs.io/en/latest/)  is a C++ library combining a physics engine and a lightweight rendering pipeline.

**Comment by arjo129** [comment]
Thanks! @bartboogmans  I will have to start populating the repository. By any chance would you like to present these projects at the maritime working group meeting?

**Comment by arjo129** [comment]
Closing this issue as I've updated the readme.
